# Site settings
title: Concurrency patterns
email: antonio.cabreraglz@gmail.com
description: > # Comparing concurrency patterns using go and elixir
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: thetonymaster
github_username:  thetonymaster

# Build settings
markdown: kramdown
